services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=ticketing
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-pass}
      - PORT=3000
    depends_on:
      - mariadb
      - seed
    restart: unless-stopped

  seed:
    build: .
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=ticketing
    depends_on:
      - mariadb
    command: sh -c "sleep 15 && node fixtures/seed.js"
    restart: "no"

  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=ticketing
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data: 