services:
  app:
    image: PLACEHOLDER_IMAGE
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=ticketing
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-pass}
      - PORT=3000
    depends_on:
      mariadb:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
    restart: unless-stopped

  seed:
    image: PLACEHOLDER_IMAGE
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=ticketing
    depends_on:
      mariadb:
        condition: service_healthy
    command: sh -c "sleep 10 && node fixtures/seed.js"
    restart: "no"

  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=ticketing
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mariadb_data: 