version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=pass
      - DB_NAME=ticketing
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=pass
      - PORT=3000
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=ticketing
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data: 